module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          black: "#171717",
          orange: "#F25623",
          "dark-gray": "#4D4D4D",
          "light-gray": "#DEDEDE",
          white: "#FFFFFF",
          "orange-hover": "#D94115",
        },
        background: "#171717",
        foreground: "#FFFFFF",
        card: "#222222",
        "card-foreground": "#FFFFFF",
        primary: "#F25623",
        "primary-foreground": "#FFFFFF",
        secondary: "#4D4D4D",
        "secondary-foreground": "#FFFFFF",
        muted: "#4D4D4D",
        "muted-foreground": "#DEDEDE",
        accent: "#4D4D4D",
        "accent-foreground": "#FFFFFF",
        destructive: "#D94115",
        "destructive-foreground": "#FFFFFF",
        border: "rgba(255,255,255,0.1)",
        input: "#4D4D4D",
        ring: "#DEDEDE",
      },
    },
  },
  plugins: [],
};
